language: ruby
rvm: 2.5.1
dist: trusty
cache: bundler
sudo: required
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script: |
  #!/usr/bin/env bash
  set -ex

  echo "Installing Postgres 10"
  sudo service postgresql stop
  sudo apt-get remove -q 'postgresql-*'
  sudo apt-get update -q
  sudo apt-get install -q postgresql-10 postgresql-client-10
  sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf

  echo "Restarting Postgres 10"
  sudo service postgresql restart
services:
  - redis-server
script:
  - PGPASSWORD="" PGUSERNAME=postgres ./bin/ci